export enum AUTH_ACTION_TYPES {
    SIGN_IN_WITH_EMAIL_START = "redux/auth/SIGN_IN_WITH_EMAIL_START",
    SIGN_IN_SUCCESS = "redux/auth/SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE = "redux/auth/SIGN_IN_FAILURE",
    SIGN_UP_START = "redux/auth/SIGN_UP_START",
    SIGN_UP_SUCCESS = "redux/auth/SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE = "redux/auth/SIGN_UP_FAILURE",
    ACCESS_TOKEN_START = "redux/auth/ACCESS_TOKEN_START",
    ACCESS_TOKEN_SUCCESS = "redux/auth/ACCESS_TOKEN_SUCCESS",
    ACCESS_TOKEN_FAILURE = "redux/auth/ACCESS_TOKEN_FAILURE",
    SIGN_OUT_START = "redux/auth/SIGN_OUT_START",
    SIGN_OUT_SUCCESS = "redux/auth/SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE = "redux/auth/SIGN_OUT_FAILURE"
}
