export enum USER_ACTION_TYPES {
    SET_CURRENT_USER_START = "redux/user/SET_CURRENT_USER_START",
    SET_CURRENT_USER_SUCCESS = "redux/user/SET_CURRENT_USER_SUCCESS",
    SET_CURRENT_USER_FAILURE = "redux/user/SET_CURRENT_USER_FAILURE",
}
