name: Perch Integrations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client-install:
    name: Install Perch client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Install Perch Client with NPM
        run: |
          cd perch-ui
          npm install

  client-test:
    name: Test Perch client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Test Perch Client with NPM
        run: |
          cd perch-ui
          npm install
          npm test

  client-build:
    name: Build Perch client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Build Perch Client with NPM
        run: |
          cd perch-ui
          npm install
          npm run build

  service-install:
    name: Install Perch service on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Install Perch Service with Maven
        run: |
          cd perch
          mvn -e -X clean install -DskipTests -Dstatic.build.skip=true

  service-test:
    name: Test Perch service on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
      - name: Test Perch Service with Maven
        run: |
          cd perch
          mvn -e -X test -Dstatic.build.skip=true

  perch-package:
    name: Package Perch on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '18'
    - name: Build Perch with Maven
      run: |
        cd perch
        mvn -e -X package -DskipTests
